// <auto-generated />
using DevPortal.QueryStack;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using System;

namespace DevPortal.QueryStack.Migrations
{
    [DbContext(typeof(DevPortalDbContext))]
    [Migration("20180825072944_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DevPortal.QueryStack.Model.Activity", b =>
                {
                    b.Property<Guid>("ActivityId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Action");

                    b.Property<Guid>("ContentId");

                    b.Property<string>("ContentTitle");

                    b.Property<string>("ContentType");

                    b.Property<string>("ExternalUrl");

                    b.Property<DateTime>("TimeStamp");

                    b.Property<string>("UserName");

                    b.HasKey("ActivityId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("DevPortal.QueryStack.Model.Blog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("Description");

                    b.Property<string>("ExternalUrl");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("DevPortal.QueryStack.Model.ContentBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<DateTime>("LastModified");

                    b.Property<string>("LastModifiedBy");

                    b.HasKey("Id");

                    b.ToTable("ContentBase");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ContentBase");
                });

            modelBuilder.Entity("DevPortal.QueryStack.Model.Tag", b =>
                {
                    b.Property<Guid>("ContentId");

                    b.Property<string>("Name");

                    b.HasKey("ContentId", "Name");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("DevPortal.QueryStack.Model.TagsUsage", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Count");

                    b.HasKey("Name");

                    b.ToTable("TagsUsage");
                });

            modelBuilder.Entity("DevPortal.QueryStack.Model.ForumPost", b =>
                {
                    b.HasBaseType("DevPortal.QueryStack.Model.ContentBase");

                    b.Property<Guid?>("ThreadId");

                    b.HasIndex("ThreadId");

                    b.ToTable("ForumPost");

                    b.HasDiscriminator().HasValue("ForumPost");
                });

            modelBuilder.Entity("DevPortal.QueryStack.Model.GenericContent", b =>
                {
                    b.HasBaseType("DevPortal.QueryStack.Model.ContentBase");

                    b.Property<string>("Title");

                    b.ToTable("GenericContent");

                    b.HasDiscriminator().HasValue("GenericContent");
                });

            modelBuilder.Entity("DevPortal.QueryStack.Model.NewsItemComment", b =>
                {
                    b.HasBaseType("DevPortal.QueryStack.Model.ContentBase");

                    b.Property<Guid?>("NewsItemId");

                    b.HasIndex("NewsItemId");

                    b.ToTable("NewsItemComment");

                    b.HasDiscriminator().HasValue("NewsItemComment");
                });

            modelBuilder.Entity("DevPortal.QueryStack.Model.ForumThread", b =>
                {
                    b.HasBaseType("DevPortal.QueryStack.Model.GenericContent");

                    b.Property<DateTime>("LastPosted");

                    b.Property<string>("LastPostedBy");

                    b.Property<string>("ParticipantsCsv");

                    b.Property<int>("PostsCount");

                    b.ToTable("ForumThread");

                    b.HasDiscriminator().HasValue("ForumThread");
                });

            modelBuilder.Entity("DevPortal.QueryStack.Model.NewsItem", b =>
                {
                    b.HasBaseType("DevPortal.QueryStack.Model.GenericContent");

                    b.Property<int>("CommentsCount");

                    b.Property<bool>("IsPublished");

                    b.Property<DateTime>("Published");

                    b.ToTable("NewsItem");

                    b.HasDiscriminator().HasValue("NewsItem");
                });

            modelBuilder.Entity("DevPortal.QueryStack.Model.Tag", b =>
                {
                    b.HasOne("DevPortal.QueryStack.Model.GenericContent")
                        .WithMany("Tags")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DevPortal.QueryStack.Model.ForumPost", b =>
                {
                    b.HasOne("DevPortal.QueryStack.Model.ForumThread", "Thread")
                        .WithMany("Posts")
                        .HasForeignKey("ThreadId");
                });

            modelBuilder.Entity("DevPortal.QueryStack.Model.NewsItemComment", b =>
                {
                    b.HasOne("DevPortal.QueryStack.Model.NewsItem")
                        .WithMany("Comments")
                        .HasForeignKey("NewsItemId");
                });
#pragma warning restore 612, 618
        }
    }
}
