// <auto-generated />
using DevPortal.CommandStack.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DevPortal.CommandStack.Migrations
{
    [DbContext(typeof(EventsDbContext))]
    [Migration("20180825075809_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DevPortal.CommandStack.Infrastructure.EventWrapper", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BlogId");

                    b.Property<string>("EventType")
                        .IsRequired();

                    b.Property<Guid?>("ForumThreadId");

                    b.Property<Guid?>("NewsItemId");

                    b.Property<string>("SerializedEvent")
                        .IsRequired();

                    b.Property<DateTime>("TimeStamp");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.HasIndex("EventType");

                    b.HasIndex("ForumThreadId");

                    b.HasIndex("NewsItemId");

                    b.HasIndex("TimeStamp");

                    b.ToTable("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
