// <auto-generated />
using System;
using DevPortal.CommandStack.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DevPortal.CommandStack.Migrations
{
    [DbContext(typeof(EventsDbContext))]
    partial class EventsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DevPortal.CommandStack.Infrastructure.EventWrapper", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BlogId");

                    b.Property<long>("EventNumber")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EventType")
                        .IsRequired();

                    b.Property<Guid?>("ForumThreadId");

                    b.Property<Guid?>("NewsItemId");

                    b.Property<string>("SerializedEvent")
                        .IsRequired();

                    b.Property<DateTime>("TimeStamp");

                    b.HasKey("Id");

                    b.HasAlternateKey("EventNumber")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("BlogId");

                    b.HasIndex("EventType");

                    b.HasIndex("ForumThreadId");

                    b.HasIndex("NewsItemId");

                    b.HasIndex("TimeStamp");

                    b.ToTable("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
