using System;
using System.Collections.Generic;
using System.Text;

namespace Migration.Crawler
{
    public static class Utils
    {
        public static string[] Spammers = new[] { "xmhlxzybzzyq998", "bfdgfdhfdhfd06", "pmpindia123", "quickydocs", "moneypower", "aliji00786", "ieltsaustralia",
            "anirbannand", "chenyan94", "ieltsnancy", "vipducs", "realspells", "Swtor2credits",
            "agbortabine", "rsorderforgame", "zhangzk",
"banlichengjidan"                          ,
"bhlxodet"                                 ,
"blair2019"                                ,
"Carmelo"                                  ,
"caster"                                   ,
"chiefspells"                              ,
"erkinssss"                                ,
"Gamerzone"                                ,
"ieltsdian"                                ,
"ieltsindia"                               ,
"ietsboss"                                 ,
"james"                                    ,
"kamara"                                   ,
"kingspells0"                              ,
"kingspells1"                              ,
"ludacrisxy"                               ,
"luxelefrance"                             ,
"maxx30"                                   ,
"Mkmane"                                   ,
"nativehealer1"                            ,
"nxljpqut"                                 ,
"penpe345"                                 ,
"pinkcoke"                                 ,
"powerfulspells"                           ,
"powerfulspells0"                          ,
"rourou"                                   ,
"rs3gold5"                                 ,
"sdfgdfgsdfdf10"                           ,
"tufjfgjfgtedfgf0"                         ,
"vishalji8"                                ,
"yhkcwsvx",
"ASDqwelk",
"nvbach",
"james621lara",
"John888",
"linchao",
"felix102",
"hotmaillogin",
"bigdaddykush",
"rilaiba014",
"Rskingdom",
"laopwai018",
"laopwai012",
"jiangyou011",
"alihair",
"pojiriy",
"ailsa",
"fasdfsafas01",
"relaiki01",
"eielai013",
"eielai01",
"qwilaihd01",
"datousr01",
"dasglaid00",
"hongwei28",
"ninadbaz017",
"ninadbaz014",
"lairlxin012",
"laibalxin012",
"ewriujfhe08",
"laoshukd014",
"laoshukd01",
"fggdger01",
"ewriujfhe10",
"shuangbin10",
"irevessab",
"ewriujfhe09",
"xbhyjkazm01",
"dyellhghghg002",
"hulisozi",
"panxing18",
"liny195",
"huangjian123",
"LeeZyn",
"Nordine1",
"yudan18",
"Juce22",
"mmotony",};
    }
}
